Repository depromeet/Took-BE, pull requests merged in 2025-04, with the labels that each got.

#87 [Feat] 로깅 시스템 구축 및 IP 차단 메커니즘 구현
  src/main/java/com/evenly/took/feature/auth/api/AuthController.java
  src/main/java/com/evenly/took/feature/user/dao/BlacklistedIPRepository.java
  src/main/java/com/evenly/took/feature/user/domain/BlacklistedIP.java
  src/main/java/com/evenly/took/feature/user/domain/vo/RequestCounter.java
  src/main/java/com/evenly/took/global/logging/config/HttpLoggingConfig.java
  src/main/java/com/evenly/took/global/logging/config/LoggingFilterConfig.java
  src/main/java/com/evenly/took/global/logging/dto/PrivacySensitiveDataInfo.java
  src/main/java/com/evenly/took/global/logging/filter/ContentCachingFilter.java
  src/main/java/com/evenly/took/global/logging/filter/HttpTraceLoggingFilter.java
  src/main/java/com/evenly/took/global/logging/filter/RateLimitingFilter.java
  src/main/java/com/evenly/took/global/logging/logger/RequestResponseLogger.java
  src/main/java/com/evenly/took/global/logging/meta/PrivacySensitiveLogging.java
  src/main/resources/application.yml
  src/main/resources/logback-spring.xml
  src/test/java/com/evenly/took/global/logging/BlacklistedIPLoggingTest.java
  src/test/resources/application-test.yml
Labels: ✨ Feature, ✅ Test, size/XL

#84 [Deploy] 프로덕션 배포 환경 구축
  .github/workflows/cd.production.yml
Labels: size/M

#90 [Refactor] multipart 파일 업로드 용량 증가
  src/main/resources/application.yml
Labels: ♻️ Refactor, size/XS

#92 [Refactor] 명함 상세 조회 API 응답값 추가
  src/main/java/com/evenly/took/feature/card/api/CardController.java
  src/main/java/com/evenly/took/feature/card/application/CardService.java
  src/main/java/com/evenly/took/feature/card/dto/response/CardDetailResponse.java
  src/test/java/com/evenly/took/feature/card/api/CardIntegrationTest.java
Labels: ♻️ Refactor, size/S

#97 [Feat] 기본 크롤러 링크 및 이미지 응답 방식 수정
  src/main/java/com/evenly/took/feature/card/client/LinkSource.java
  src/main/java/com/evenly/took/feature/card/client/crawler/BasicLinkCrawler.java
  src/main/java/com/evenly/took/feature/card/exception/CardErrorCode.java
Labels: size/M

#99 [Feat] 회원탈퇴 시 이유 추가
  src/main/java/com/evenly/took/feature/auth/api/AuthApi.java
  src/main/java/com/evenly/took/feature/auth/api/AuthController.java
  src/main/java/com/evenly/took/feature/auth/application/AuthService.java
  src/main/java/com/evenly/took/feature/auth/application/WithdrawService.java
  src/main/java/com/evenly/took/feature/auth/dto/request/WithdrawRequest.java
  src/main/java/com/evenly/took/feature/card/domain/vo/WithdrawReasons.java
  src/main/java/com/evenly/took/feature/user/domain/User.java
  src/test/java/com/evenly/took/feature/auth/api/AuthIntegrationTest.java
  src/test/java/com/evenly/took/feature/auth/application/AuthServiceTest.java
  src/test/java/com/evenly/took/feature/auth/application/WithdrawServiceTest.java
  src/test/java/com/evenly/took/global/domain/UserBase.java
  src/test/java/com/evenly/took/global/domain/UserFactory.java
  src/test/java/com/evenly/took/global/domain/UserFixture.java
Labels: ✨ Feature, size/L

#100 [Refactor] 받은 명함 ID DESC 정렬 및 이미지 조회 시 PresignedLink 활용
  src/main/java/com/evenly/took/feature/card/application/CardService.java
  src/main/java/com/evenly/took/feature/card/dao/ReceivedCardRepository.java
  src/main/java/com/evenly/took/feature/card/domain/Card.java
  src/main/java/com/evenly/took/feature/card/domain/CardImage.java
  src/main/java/com/evenly/took/feature/card/domain/CardImageUrlFetcher.java
  src/main/resources/application.yml
  src/test/java/com/evenly/took/feature/card/api/CardIntegrationTest.java
  src/test/resources/application-test.yml
Labels: ♻️ Refactor, ✅ Test, size/L

#101 [Refactor] 받은명함 정렬을 위한 timestamp 응답 추가
  src/main/java/com/evenly/took/feature/card/application/CardService.java
  src/main/java/com/evenly/took/feature/card/dto/response/ReceivedCardListResponse.java
  src/main/java/com/evenly/took/feature/card/dto/response/ReceivedCardResponse.java
  src/main/java/com/evenly/took/feature/card/mapper/CardMapper.java
Labels: ♻️ Refactor, size/M

#103 [Feat] 내 명함 삭제 API
  src/main/java/com/evenly/took/feature/card/api/CardApi.java
  src/main/java/com/evenly/took/feature/card/api/CardController.java
  src/main/java/com/evenly/took/feature/card/application/CardService.java
  src/main/java/com/evenly/took/feature/card/domain/Card.java
  src/main/java/com/evenly/took/feature/card/exception/CardErrorCode.java
  src/main/java/com/evenly/took/global/response/SuccessResponse.java
Labels: size/M

#104 [Deploy] 프로덕션 배포
  src/main/java/com/evenly/took/feature/card/api/CardApi.java
  src/main/java/com/evenly/took/feature/card/api/CardController.java
  src/main/java/com/evenly/took/feature/card/application/CardService.java
  src/main/java/com/evenly/took/feature/card/domain/Card.java
  src/main/java/com/evenly/took/feature/card/dto/response/ReceivedCardListResponse.java
  src/main/java/com/evenly/took/feature/card/dto/response/ReceivedCardResponse.java
  src/main/java/com/evenly/took/feature/card/exception/CardErrorCode.java
  src/main/java/com/evenly/took/feature/card/mapper/CardMapper.java
  src/main/java/com/evenly/took/global/response/SuccessResponse.java
Labels: 🚀 Deploy, size/L

#113 [Feat] 명함 수정 API 구현
  src/main/java/com/evenly/took/feature/card/api/CardApi.java
  src/main/java/com/evenly/took/feature/card/api/CardController.java
  src/main/java/com/evenly/took/feature/card/application/CardService.java
  src/main/java/com/evenly/took/feature/card/domain/Card.java
  src/main/java/com/evenly/took/feature/card/dto/request/FixCardRequest.java
  src/main/java/com/evenly/took/feature/card/exception/CardErrorCode.java
  src/main/java/com/evenly/took/global/aws/s3/S3ServiceImpl.java
  src/test/java/com/evenly/took/feature/card/api/CardIntegrationTest.java
  src/test/java/com/evenly/took/global/config/testcontainers/S3TestConfig.java
  src/test/resources/application-test.yml
Labels: size/XL

#63 [Feat] Redis Geospatial을 활용한 위치 기반 서비스 구현
  src/main/java/com/evenly/took/global/redis/RedisGeoSpatialService.java
  src/main/java/com/evenly/took/global/redis/RedisGeoSpatialServiceImpl.java
  src/main/java/com/evenly/took/global/redis/dto/NearbyUserDto.java
  src/main/java/com/evenly/took/global/redis/dto/SearchParameters.java
  src/test/java/com/evenly/took/global/redis/RedisGeoSpatialTest.java
Labels: ✨ Feature, ✅ Test, size/XL

#109 [Feat] Slack 오류 로그 알림 추가
  build.gradle
  src/main/java/com/evenly/took/feature/auth/api/AuthController.java
  src/main/java/com/evenly/took/feature/card/api/CardController.java
  src/main/java/com/evenly/took/global/health/HealthController.java
  src/main/java/com/evenly/took/global/monitoring/slack/SlackErrorAlert.java
  src/main/java/com/evenly/took/global/monitoring/slack/SlackErrorAlertAspect.java
  src/main/java/com/evenly/took/global/monitoring/slack/SlackService.java
  src/main/resources/application-prod.yml
Labels: ✨ Feature, size/L

#111 [Feat] 대표 명함 설정 및 조회
  src/main/java/com/evenly/took/feature/card/api/CardApi.java
  src/main/java/com/evenly/took/feature/card/api/CardController.java
  src/main/java/com/evenly/took/feature/card/application/CardService.java
  src/main/java/com/evenly/took/feature/card/dao/CardRepository.java
  src/main/java/com/evenly/took/feature/card/domain/Card.java
  src/main/java/com/evenly/took/feature/card/dto/response/CardResponse.java
  src/main/java/com/evenly/took/feature/card/mapper/CardMapper.java
  src/test/java/com/evenly/took/feature/card/api/CardIntegrationTest.java
  src/test/java/com/evenly/took/feature/card/application/CardServiceTest.java
  src/test/java/com/evenly/took/global/domain/CardBase.java
  src/test/java/com/evenly/took/global/domain/CardFixture.java
Labels: ✨ Feature, size/XL

#117 [Feat] 최근 받은 명함 목록 조회
  src/main/java/com/evenly/took/feature/card/api/CardApi.java
  src/main/java/com/evenly/took/feature/card/api/CardController.java
  src/main/java/com/evenly/took/feature/card/application/CardService.java
  src/main/java/com/evenly/took/feature/card/dao/CardRepository.java
  src/main/java/com/evenly/took/feature/card/dao/ReceivedCardRepository.java
  src/main/java/com/evenly/took/feature/card/dto/request/NewReceivedCardsRequest.java
  src/main/java/com/evenly/took/feature/card/exception/CardErrorCode.java
  src/test/java/com/evenly/took/feature/card/api/CardIntegrationTest.java
  src/test/java/com/evenly/took/global/domain/CardFixture.java
Labels: size/XL

#119 [Feat] 한 줄 메모 여러개의 명함에 동시에 업데이트 API
  src/main/java/com/evenly/took/feature/card/api/CardApi.java
  src/main/java/com/evenly/took/feature/card/api/CardController.java
  src/main/java/com/evenly/took/feature/card/application/CardService.java
  src/main/java/com/evenly/took/feature/card/dto/request/SetReceivedCardsMemoRequest.java
  src/test/java/com/evenly/took/feature/card/api/CardIntegrationTest.java
Labels: ✨ Feature, ✅ Test, size/L

#115 [Feat] 유저의 현재 위치 등록 갱신 작업 및 주변 유저 조회
  src/main/java/com/evenly/took/feature/auth/api/AuthController.java
  src/main/java/com/evenly/took/feature/card/api/CardApi.java
  src/main/java/com/evenly/took/feature/card/api/CardController.java
  src/main/java/com/evenly/took/feature/card/application/CardService.java
  src/main/java/com/evenly/took/feature/card/dao/CardRepository.java
  src/main/java/com/evenly/took/feature/card/domain/Card.java
  src/main/java/com/evenly/took/feature/card/dto/request/SendCardRequest.java
  src/main/java/com/evenly/took/feature/notification/application/NotificationEventListener.java
  src/main/java/com/evenly/took/feature/user/api/UserApi.java
  src/main/java/com/evenly/took/feature/user/api/UserController.java
  src/main/java/com/evenly/took/feature/user/application/FindNearbyUserService.java
  src/main/java/com/evenly/took/feature/user/dto/response/NearbyUserBasicProfileResponse.java
  src/main/java/com/evenly/took/feature/user/dto/response/NearbyUserCardProfileResponse.java
  src/main/java/com/evenly/took/feature/user/dto/response/NearbyUserProfileListResponse.java
  src/main/java/com/evenly/took/feature/user/dto/response/NearbyUserProfileResponse.java
  src/main/java/com/evenly/took/feature/user/mapper/NearbyUserProfileMapper.java
  src/main/java/com/evenly/took/global/location/LocationErrorCode.java
  src/main/java/com/evenly/took/global/location/aspect/LocationRegistrationAspect.java
  src/main/java/com/evenly/took/global/location/config/LocationAsyncConfig.java
  src/main/java/com/evenly/took/global/location/event/LocationRegistrationEvent.java
  src/main/java/com/evenly/took/global/location/event/LocationRegistrationEventHandler.java
  src/main/java/com/evenly/took/global/location/meta/RegisterLocation.java
  src/main/java/com/evenly/took/global/location/util/LocationHeaderParser.java
  src/main/java/com/evenly/took/global/redis/RedisGeoSpatialService.java
  src/main/java/com/evenly/took/global/redis/RedisGeoSpatialServiceImpl.java
  src/test/java/com/evenly/took/feature/card/api/CardIntegrationTest.java
  src/test/java/com/evenly/took/feature/card/application/CardServiceTest.java
  src/test/java/com/evenly/took/feature/notification/application/NotificationServiceTest.java
  src/test/java/com/evenly/took/feature/user/api/LocationRegistrationIntegrationTest.java
  src/test/java/com/evenly/took/feature/user/api/NearbyUserIntegrationTest.java
  src/test/java/com/evenly/took/feature/user/application/FindNearbyUserServiceTest.java
  src/test/java/com/evenly/took/global/helper/MysqlCleaner.java
  src/test/java/com/evenly/took/global/integration/JwtMockIntegrationTest.java
  src/test/java/com/evenly/took/global/redis/RedisGeoSpatialTest.java
Labels: ✨ Feature, size/XXL

#123 [Deploy] Production 배포
  src/main/java/com/evenly/took/feature/user/domain/AllowPush.java
  src/main/java/com/evenly/took/feature/user/domain/User.java
  src/main/java/com/evenly/took/feature/user/dto/response/AllowNotificationResponse.java
Labels: size/XS

#125 [Fix] User AllowPush 초기화 문제 해결
  src/main/java/com/evenly/took/feature/auth/client/apple/AppleUserClient.java
  src/main/java/com/evenly/took/feature/auth/client/google/GoogleUserClient.java
  src/main/java/com/evenly/took/feature/auth/client/kakao/KakaoUserClient.java
Labels: 🐛 Fix, size/S

#126 [Fix] User AllowPush fix
  src/main/java/com/evenly/took/feature/auth/client/apple/AppleUserClient.java
  src/main/java/com/evenly/took/feature/auth/client/google/GoogleUserClient.java
  src/main/java/com/evenly/took/feature/auth/client/kakao/KakaoUserClient.java
Labels: 🐛 Fix, size/S

#128 [Refactor] 명함 상세정보에 previewInfo 정보 추가
  src/main/java/com/evenly/took/feature/card/application/CardService.java
  src/main/java/com/evenly/took/feature/card/dto/response/CardDetailResponse.java
  src/main/java/com/evenly/took/feature/card/mapper/CardMapper.java
Labels: size/S

#127 [Fix] slack alert condition update
  src/main/java/com/evenly/took/global/monitoring/slack/SlackErrorAlertAspect.java
Labels: 🐛 Fix, size/S

#129 [Test] Card Detail response Test 수정
  src/test/java/com/evenly/took/feature/card/api/CardIntegrationTest.java
Labels: ✅ Test, size/M

#130 [Deploy] Production 배포
  src/main/java/com/evenly/took/feature/card/application/CardService.java
  src/main/java/com/evenly/took/feature/card/dto/response/CardDetailResponse.java
  src/main/java/com/evenly/took/feature/card/mapper/CardMapper.java
  src/main/java/com/evenly/took/global/monitoring/slack/SlackErrorAlertAspect.java
  src/test/java/com/evenly/took/feature/card/api/CardIntegrationTest.java
Labels: 🚀 Deploy, 🐛 Fix, size/M

#131 feat: expoToken만 null인 경우 처리
  src/main/java/com/evenly/took/feature/auth/application/AuthService.java
Labels: size/XS

#133 [Feat] 알림 목록 조회 페이지 type 필드 추가
  src/main/java/com/evenly/took/feature/notification/dto/NotificationResponse.java
Labels: size/S

#136 [Deploy] Production 배포
  src/main/java/com/evenly/took/feature/notification/domain/NotificationData.java
  src/main/java/com/evenly/took/feature/notification/domain/NotificationType.java
  src/main/java/com/evenly/took/feature/notification/dto/NotificationResponse.java
  src/main/java/com/evenly/took/feature/user/api/UserController.java
  src/main/java/com/evenly/took/feature/user/application/UserService.java
  src/main/java/com/evenly/took/feature/user/domain/AllowPushContent.java
  src/main/java/com/evenly/took/feature/user/dto/request/AllowNotificationRequest.java
  src/main/java/com/evenly/took/feature/user/dto/request/AllowPushContentMapper.java
  src/main/java/com/evenly/took/feature/user/dto/response/AllowNotificationResponse.java
  src/main/java/com/evenly/took/feature/user/exception/UserErrorCode.java
  src/test/java/com/evenly/took/feature/user/api/UserIntegrationTest.java
Labels: 🚀 Deploy, size/L

#138 [Fix] Redis GEO 위치 등록 비동기 이벤트 수정
  src/main/java/com/evenly/took/global/location/config/LocationAsyncConfig.java
  src/main/java/com/evenly/took/global/location/event/LocationRegistrationEventHandler.java
  src/main/java/com/evenly/took/global/redis/RedisGeoSpatialServiceImpl.java
Labels: 🐛 Fix, size/S

#139 [Deploy] Redis GEO 위치 등록 비동기 이벤트 수정 배포
  src/main/java/com/evenly/took/global/location/config/LocationAsyncConfig.java
  src/main/java/com/evenly/took/global/location/event/LocationRegistrationEventHandler.java
  src/main/java/com/evenly/took/global/redis/RedisGeoSpatialServiceImpl.java
Labels: 🚀 Deploy, size/S
