Repository depromeet/Took-BE, pull requests merged in 2025-02, with the labels that each got.

#6 [Feat] security config 설정
  build.gradle
  src/main/java/com/evenly/blok/global/config/security/WebSecurityConfig.java
Labels: ✨ Feature

#5 [Feat] DB 세팅 및 배포 플로우 자동화 기본 작업
  .github/workflows/cd.develop.yml
  Dockerfile
  build.gradle
  docker-compose.yml
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
Labels: 🚀 Deploy, ✨ Feature

#4 [Feat] 전역적 예외 및 핸들러 추가
  src/main/java/com/evenly/blok/global/exception/BlokException.java
  src/main/java/com/evenly/blok/global/exception/CommonErrorCode.java
  src/main/java/com/evenly/blok/global/exception/ErrorCode.java
  src/main/java/com/evenly/blok/global/exception/GlobalExceptionHandler.java
  src/main/java/com/evenly/blok/global/exception/dto/ErrorResponse.java
  src/main/java/com/evenly/blok/global/exception/dto/ServerErrorResponse.java
  src/main/java/com/evenly/blok/global/exception/dto/ValidationErrorResponse.java
  src/main/java/com/evenly/blok/global/response/GlobalResponseHandler.java
  src/main/java/com/evenly/blok/global/response/SuccessResponse.java
Labels: ✨ Feature

#9 [Feat] 테스트 통합 환경 구축
  build.gradle
  src/main/java/com/evenly/blok/global/common/constants/EnvironmentConstants.java
  src/main/java/com/evenly/blok/global/config/swagger/SwaggerConfig.java
  src/main/resources/appication-dev.yml
  src/main/resources/application-dev.yml
  src/test/java/com/evenly/blok/global/config/TestcontainersConfig.java
  src/test/java/com/evenly/blok/global/controller/ControllerTest.java
  src/test/java/com/evenly/blok/global/health/HealthControllerIntegrationTest.java
  src/test/java/com/evenly/blok/global/health/HealthControllerTest.java
  src/test/java/com/evenly/blok/global/integration/IntegrationTest.java
  src/test/java/com/evenly/blok/global/repository/RepositoryTest.java
  src/test/java/com/evenly/blok/global/service/MockTest.java
  src/test/resources/application-test.yml
Labels: ✨ Feature, ✅ Test

#10 [Feat] Private RDS 로컬 EC2 인스턴스 터널링 작업
  .gitignore
  build.gradle
  src/main/java/com/evenly/blok/global/config/datasource/SshDataSourceConfig.java
  src/main/java/com/evenly/blok/global/config/ssh/SshTunnelingInitializer.java
  src/main/resources/application-local.yml
Labels: ✨ Feature

#13 [Feat] GitAction CI workflow 구현
  .github/CODEOWNERS
  .github/workflows/ci.yml
Labels: 🚀 Deploy

#14 [Feat] 초기 세팅 작업 완료
  .github/CODEOWNERS
  .github/workflows/cd.develop.yml
  .github/workflows/ci.yml
  .github/workflows/pr-size-labeler.yml
  .gitignore
  Dockerfile
  README.md
  build.gradle
  docker-compose.yml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/evenly/took/TookApplication.java
  src/main/java/com/evenly/took/global/common/constants/EnvironmentConstants.java
  src/main/java/com/evenly/took/global/common/constants/UrlConstants.java
  src/main/java/com/evenly/took/global/config/datasource/SshDataSourceConfig.java
  src/main/java/com/evenly/took/global/config/security/WebSecurityConfig.java
  src/main/java/com/evenly/took/global/config/ssh/SshTunnelingInitializer.java
  src/main/java/com/evenly/took/global/config/swagger/SwaggerConfig.java
  src/main/java/com/evenly/took/global/exception/CommonErrorCode.java
  src/main/java/com/evenly/took/global/exception/ErrorCode.java
  src/main/java/com/evenly/took/global/exception/GlobalExceptionHandler.java
  src/main/java/com/evenly/took/global/exception/TookException.java
  src/main/java/com/evenly/took/global/exception/dto/ErrorResponse.java
  src/main/java/com/evenly/took/global/exception/dto/ServerErrorResponse.java
  src/main/java/com/evenly/took/global/exception/dto/ValidationErrorResponse.java
  src/main/java/com/evenly/took/global/health/HealthApi.java
  src/main/java/com/evenly/took/global/health/HealthController.java
  src/main/java/com/evenly/took/global/response/GlobalResponseHandler.java
  src/main/java/com/evenly/took/global/response/SuccessResponse.java
  src/main/java/com/evenly/took/global/util/ProfileResolver.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/test/java/com/evenly/took/TestTookApplication.java
  src/test/java/com/evenly/took/TookApplicationTests.java
  src/test/java/com/evenly/took/global/config/TestcontainersConfig.java
  src/test/java/com/evenly/took/global/controller/ControllerTest.java
  src/test/java/com/evenly/took/global/health/HealthControllerIntegrationTest.java
  src/test/java/com/evenly/took/global/health/HealthControllerTest.java
  src/test/java/com/evenly/took/global/integration/IntegrationTest.java
  src/test/java/com/evenly/took/global/repository/RepositoryTest.java
  src/test/java/com/evenly/took/global/service/MockTest.java
  src/test/resources/application-test.yml
Labels: 🚀 Deploy, ✨ Feature, ✅ Test, size/XXL

#16 [Fix] Swagger 환경별 url 설정 수정
  src/main/java/com/evenly/took/global/common/constants/EnvironmentConstants.java
  src/main/java/com/evenly/took/global/common/constants/UrlConstants.java
  src/main/java/com/evenly/took/global/config/swagger/SwaggerConfig.java
  src/main/java/com/evenly/took/global/util/ProfileResolver.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/test/java/com/evenly/took/global/controller/ControllerTest.java
  src/test/java/com/evenly/took/global/integration/IntegrationTest.java
  src/test/java/com/evenly/took/global/repository/RepositoryTest.java
  src/test/java/com/evenly/took/global/service/MockTest.java
Labels: 🐛 Fix, size/XS

#19 [Feat] PR 플로우 개선 작업
  .coderabbit.yaml
  .github/workflows/pr-size-labeler.yml
Labels: ✨ Feature, size/M

#23 [Feat] Redis 환경 구성 및 테스트 플로우 구축
  .github/workflows/cd.develop.yml
  Dockerfile
  build.gradle
  docker-compose.yml
  src/main/java/com/evenly/took/feature/user/dao/UserRepository.java
  src/main/java/com/evenly/took/global/config/redis/RedisConfig.java
  src/main/java/com/evenly/took/global/config/ssh/SshTunnelingInitializer.java
  src/main/java/com/evenly/took/global/redis/RedisService.java
  src/main/java/com/evenly/took/global/redis/RedisServiceImpl.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/test/java/com/evenly/took/TestTookApplication.java
  src/test/java/com/evenly/took/global/config/testcontainers/MySQLTestConfig.java
  src/test/java/com/evenly/took/global/config/testcontainers/RedisTestConfig.java
  src/test/java/com/evenly/took/global/redis/RedisTest.java
  src/test/resources/application-test.yml
Labels: ✨ Feature, ✅ Test, size/L
