Repository depromeet/Took-BE, pull requests merged in 2025-03, with the labels that each got.

#31 [Feat] 카카오 로그인 구현
  src/main/java/com/evenly/took/feature/auth/application/JwtTokenProvider.java
  src/main/java/com/evenly/took/feature/auth/application/UuidTokenProvider.java
  src/main/java/com/evenly/took/feature/auth/client/kakao/KakaoAuthCodeRequestUrlProvider.java
  src/main/java/com/evenly/took/feature/auth/client/kakao/KakaoTokenProvider.java
  src/main/java/com/evenly/took/feature/auth/client/kakao/KakaoUserClient.java
  src/main/java/com/evenly/took/feature/auth/client/kakao/KakaoUserInfoProvider.java
  src/main/java/com/evenly/took/feature/auth/client/kakao/dto/request/KakaoTokenRequest.java
  src/main/java/com/evenly/took/feature/auth/client/kakao/dto/response/KakaoErrorResponse.java
  src/main/java/com/evenly/took/feature/auth/client/kakao/dto/response/KakaoTokenResponse.java
  src/main/java/com/evenly/took/feature/auth/client/kakao/dto/response/KakaoUserAccount.java
  src/main/java/com/evenly/took/feature/auth/client/kakao/dto/response/KakaoUserResponse.java
  src/main/java/com/evenly/took/feature/auth/client/kakao/error/KakaoTokenProviderErrorHandler.java
  src/main/java/com/evenly/took/feature/auth/client/kakao/error/KakaoUserInfoProviderErrorHandler.java
  src/main/java/com/evenly/took/feature/auth/config/AuthConfig.java
  src/main/java/com/evenly/took/feature/auth/exception/AuthErrorCode.java
  src/main/java/com/evenly/took/feature/common/exception/CommonErrorCode.java
  src/main/java/com/evenly/took/feature/common/exception/TookException.java
  src/main/java/com/evenly/took/global/config/properties/PropertiesConfig.java
  src/main/java/com/evenly/took/global/config/properties/auth/KakaoProperties.java
  src/main/java/com/evenly/took/global/config/properties/auth/KakaoUrlProperties.java
  src/main/java/com/evenly/took/global/config/properties/auth/TokenProperties.java
  src/main/java/com/evenly/took/global/exception/GlobalExceptionHandler.java
  src/main/java/com/evenly/took/global/exception/dto/RequestParameterErrorResponse.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/test/java/com/evenly/took/feature/auth/api/AuthIntegrationTest.java
  src/test/java/com/evenly/took/feature/auth/application/JwtTokenProviderTest.java
  src/test/java/com/evenly/took/feature/auth/application/UuidTokenProviderTest.java
  src/test/java/com/evenly/took/feature/auth/client/kakao/KakaoTokenProviderTest.java
  src/test/java/com/evenly/took/feature/auth/client/kakao/KakaoUserInfoProviderTest.java
  src/test/java/com/evenly/took/global/service/BaseRestClientTest.java
  src/test/resources/application-test.yml
  src/test/resources/auth/kakao/error-invalid-access-token.json
  src/test/resources/auth/kakao/error-invalid-code.json
  src/test/resources/auth/kakao/error-unhandled.json
  src/test/resources/auth/kakao/success-token-response.json
  src/test/resources/auth/kakao/success-user-info-response.json
Labels: ✨ Feature, ✅ Test, size/XL

#27 [Feat] 구글 로그인 구현
  src/main/java/com/evenly/took/feature/auth/client/google/GoogleAuthCodeRequestUrlProvider.java
  src/main/java/com/evenly/took/feature/auth/client/google/GoogleTokenProvider.java
  src/main/java/com/evenly/took/feature/auth/client/google/GoogleUserClient.java
  src/main/java/com/evenly/took/feature/auth/client/google/GoogleUserInfoProvider.java
  src/main/java/com/evenly/took/feature/auth/client/google/dto/request/GoogleTokenRequest.java
  src/main/java/com/evenly/took/feature/auth/client/google/dto/response/GoogleTokenResponse.java
  src/main/java/com/evenly/took/feature/auth/client/google/dto/response/GoogleUserInfoResponse.java
  src/main/java/com/evenly/took/feature/auth/client/google/error/GoogleTokenProviderErrorHandler.java
  src/main/java/com/evenly/took/feature/auth/client/google/error/GoogleUserInfoProviderErrorHandler.java
  src/main/java/com/evenly/took/feature/auth/exception/AuthErrorCode.java
  src/main/java/com/evenly/took/global/config/properties/auth/GoogleProperties.java
  src/main/java/com/evenly/took/global/config/properties/auth/GoogleUrlProperties.java
  src/main/java/com/evenly/took/global/config/security/WebSecurityConfig.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/test/java/com/evenly/took/feature/auth/client/google/GoogleTokenProviderTest.java
  src/test/java/com/evenly/took/feature/auth/client/google/GoogleUserClientTest.java
  src/test/java/com/evenly/took/feature/auth/client/google/GoogleUserInfoProviderTest.java
  src/test/java/com/evenly/took/feature/auth/client/google/MockGoogleProviderTest.java
Labels: ✨ Feature, ✅ Test, size/XL

#33 [Feat] 애플 로그인 구현
  src/main/java/com/evenly/took/feature/auth/api/AuthApi.java
  src/main/java/com/evenly/took/feature/auth/api/AuthController.java
  src/main/java/com/evenly/took/feature/auth/application/AuthService.java
  src/main/java/com/evenly/took/feature/auth/client/AuthContext.java
  src/main/java/com/evenly/took/feature/auth/client/UserClient.java
  src/main/java/com/evenly/took/feature/auth/client/UserClientComposite.java
  src/main/java/com/evenly/took/feature/auth/client/apple/AppleAuthCodeRequestUrlProvider.java
  src/main/java/com/evenly/took/feature/auth/client/apple/AppleTokenProvider.java
  src/main/java/com/evenly/took/feature/auth/client/apple/AppleUserClient.java
  src/main/java/com/evenly/took/feature/auth/client/apple/AppleUserInfoProvider.java
  src/main/java/com/evenly/took/feature/auth/client/apple/dto/request/AppleAuthRequest.java
  src/main/java/com/evenly/took/feature/auth/client/apple/dto/request/AppleTokenRequest.java
  src/main/java/com/evenly/took/feature/auth/client/apple/dto/response/AppleAuthUrlResponse.java
  src/main/java/com/evenly/took/feature/auth/client/apple/dto/response/AppleErrorResponse.java
  src/main/java/com/evenly/took/feature/auth/client/apple/dto/response/AppleTokenResponse.java
  src/main/java/com/evenly/took/feature/auth/client/apple/dto/response/AppleUserResponse.java
  src/main/java/com/evenly/took/feature/auth/client/apple/error/AppleErrorHandler.java
  src/main/java/com/evenly/took/feature/auth/client/apple/error/AppleTokenProviderErrorHandler.java
  src/main/java/com/evenly/took/feature/auth/client/apple/error/AppleUserInfoProviderErrorHandler.java
  src/main/java/com/evenly/took/feature/auth/client/google/GoogleUserClient.java
  src/main/java/com/evenly/took/feature/auth/client/kakao/KakaoUserClient.java
  src/main/java/com/evenly/took/feature/auth/exception/AuthErrorCode.java
  src/main/java/com/evenly/took/global/config/properties/auth/AppleProperties.java
  src/main/java/com/evenly/took/global/config/properties/auth/AppleUrlProperties.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/test/java/com/evenly/took/feature/auth/application/UserClientCompositeTest.java
  src/test/java/com/evenly/took/feature/auth/client/apple/AppleTokenProviderTest.java
  src/test/java/com/evenly/took/feature/auth/client/apple/AppleUserClientTest.java
  src/test/java/com/evenly/took/feature/auth/client/apple/AppleUserInfoProviderTest.java
  src/test/java/com/evenly/took/feature/auth/client/google/GoogleUserClientTest.java
Labels: ✨ Feature, ✅ Test, size/XXL

#35 [Refactor] 환경변수 개선 및 프로퍼티 관련 패키지 이동
  .gitignore
  src/main/java/com/evenly/took/feature/auth/application/JwtTokenProvider.java
  src/main/java/com/evenly/took/feature/auth/application/UuidTokenProvider.java
  src/main/java/com/evenly/took/feature/auth/client/apple/AppleAuthCodeRequestUrlProvider.java
  src/main/java/com/evenly/took/feature/auth/client/apple/AppleTokenProvider.java
  src/main/java/com/evenly/took/feature/auth/client/apple/dto/request/AppleAuthRequest.java
  src/main/java/com/evenly/took/feature/auth/client/apple/dto/request/AppleTokenRequest.java
  src/main/java/com/evenly/took/feature/auth/client/google/GoogleAuthCodeRequestUrlProvider.java
  src/main/java/com/evenly/took/feature/auth/client/google/GoogleTokenProvider.java
  src/main/java/com/evenly/took/feature/auth/client/google/GoogleUserInfoProvider.java
  src/main/java/com/evenly/took/feature/auth/client/google/dto/request/GoogleTokenRequest.java
  src/main/java/com/evenly/took/feature/auth/client/kakao/KakaoAuthCodeRequestUrlProvider.java
  src/main/java/com/evenly/took/feature/auth/client/kakao/KakaoTokenProvider.java
  src/main/java/com/evenly/took/feature/auth/client/kakao/KakaoUserInfoProvider.java
  src/main/java/com/evenly/took/feature/auth/client/kakao/dto/request/KakaoTokenRequest.java
  src/main/java/com/evenly/took/feature/auth/config/AuthConfig.java
  src/main/java/com/evenly/took/feature/auth/config/properties/AppleProperties.java
  src/main/java/com/evenly/took/feature/auth/config/properties/AppleUrlProperties.java
  src/main/java/com/evenly/took/feature/auth/config/properties/GoogleProperties.java
  src/main/java/com/evenly/took/feature/auth/config/properties/GoogleUrlProperties.java
  src/main/java/com/evenly/took/feature/auth/config/properties/KakaoProperties.java
  src/main/java/com/evenly/took/feature/auth/config/properties/KakaoUrlProperties.java
  src/main/java/com/evenly/took/feature/auth/config/properties/TokenProperties.java
  src/main/java/com/evenly/took/global/config/properties/PropertiesConfig.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
  src/test/java/com/evenly/took/feature/auth/application/JwtTokenProviderTest.java
  src/test/java/com/evenly/took/feature/auth/client/apple/AppleTokenProviderTest.java
  src/test/java/com/evenly/took/feature/auth/client/google/MockGoogleProviderTest.java
  src/test/java/com/evenly/took/feature/auth/client/kakao/KakaoTokenProviderTest.java
  src/test/java/com/evenly/took/feature/auth/client/kakao/KakaoUserInfoProviderTest.java
  src/test/java/com/evenly/took/global/service/BaseRestClientTest.java
  src/test/resources/application-test.yml
Labels: ♻️ Refactor, size/L

#37 [Fix] 클래스별 restClient 분리를 위해 restClientBuilder 빈 복사 후 빌드
  src/main/java/com/evenly/took/feature/auth/client/apple/AppleTokenProvider.java
  src/main/java/com/evenly/took/feature/auth/client/google/GoogleTokenProvider.java
  src/main/java/com/evenly/took/feature/auth/client/google/GoogleUserInfoProvider.java
  src/main/java/com/evenly/took/feature/auth/client/kakao/KakaoTokenProvider.java
  src/main/java/com/evenly/took/feature/auth/client/kakao/KakaoUserInfoProvider.java
  src/test/java/com/evenly/took/feature/auth/client/apple/AppleTokenProviderTest.java
  src/test/java/com/evenly/took/feature/auth/client/google/MockGoogleProviderTest.java
Labels: 🐛 Fix, size/S

#41 [Feat] 소셜 로그인 정보 추가
  src/main/java/com/evenly/took/feature/auth/client/apple/AppleUserClient.java
  src/main/java/com/evenly/took/feature/auth/client/google/GoogleUserClient.java
  src/main/java/com/evenly/took/feature/auth/client/google/dto/response/GoogleUserInfoResponse.java
  src/main/java/com/evenly/took/feature/auth/client/kakao/KakaoUserClient.java
  src/main/java/com/evenly/took/feature/auth/client/kakao/dto/response/KakaoUserAccount.java
  src/main/java/com/evenly/took/feature/auth/dto/response/UserResponse.java
  src/main/java/com/evenly/took/feature/user/domain/User.java
  src/test/java/com/evenly/took/feature/auth/application/UserClientCompositeTest.java
  src/test/java/com/evenly/took/feature/auth/client/google/GoogleUserClientTest.java
  src/test/java/com/evenly/took/feature/auth/client/google/GoogleUserInfoProviderTest.java
  src/test/java/com/evenly/took/global/domain/TestUserFactory.java
Labels: size/M

#42 [Feat] S3 서비스 구현
  build.gradle
  src/main/java/com/evenly/took/feature/auth/api/HeaderHandler.java
  src/main/java/com/evenly/took/feature/auth/application/JwtTokenProvider.java
  src/main/java/com/evenly/took/feature/auth/application/UuidTokenProvider.java
  src/main/java/com/evenly/took/feature/auth/client/AuthCodeRequestUrlProviderComposite.java
  src/main/java/com/evenly/took/feature/auth/client/UserClientComposite.java
  src/main/java/com/evenly/took/feature/auth/client/apple/AppleUserClient.java
  src/main/java/com/evenly/took/feature/auth/client/apple/AppleUserInfoProvider.java
  src/main/java/com/evenly/took/feature/auth/client/apple/error/AppleErrorHandler.java
  src/main/java/com/evenly/took/feature/auth/client/apple/error/AppleTokenProviderErrorHandler.java
  src/main/java/com/evenly/took/feature/auth/client/apple/error/AppleUserInfoProviderErrorHandler.java
  src/main/java/com/evenly/took/feature/auth/client/google/GoogleUserClient.java
  src/main/java/com/evenly/took/feature/auth/client/google/error/GoogleTokenProviderErrorHandler.java
  src/main/java/com/evenly/took/feature/auth/client/google/error/GoogleUserInfoProviderErrorHandler.java
  src/main/java/com/evenly/took/feature/auth/client/kakao/error/KakaoTokenProviderErrorHandler.java
  src/main/java/com/evenly/took/feature/auth/client/kakao/error/KakaoUserInfoProviderErrorHandler.java
  src/main/java/com/evenly/took/global/auth/AuthenticationFilter.java
  src/main/java/com/evenly/took/global/aws/properties/AwsCredentialProperties.java
  src/main/java/com/evenly/took/global/aws/properties/AwsProperties.java
  src/main/java/com/evenly/took/global/aws/properties/AwsS3Properties.java
  src/main/java/com/evenly/took/global/aws/s3/S3Service.java
  src/main/java/com/evenly/took/global/aws/s3/S3ServiceImpl.java
  src/main/java/com/evenly/took/global/aws/s3/exception/S3ErrorCode.java
  src/main/java/com/evenly/took/global/config/s3/S3Config.java
  src/main/java/com/evenly/took/global/exception/GlobalExceptionHandler.java
  src/main/java/com/evenly/took/global/exception/TookException.java
  src/main/resources/application.yml
  src/test/java/com/evenly/took/feature/auth/application/JwtTokenProviderTest.java
  src/test/java/com/evenly/took/feature/auth/application/UserClientCompositeTest.java
  src/test/java/com/evenly/took/feature/auth/application/UuidTokenProviderTest.java
  src/test/java/com/evenly/took/feature/auth/client/AuthCodeRequestUrlProviderCompositeTest.java
  src/test/java/com/evenly/took/feature/auth/client/apple/AppleUserClientTest.java
  src/test/java/com/evenly/took/feature/auth/client/apple/AppleUserInfoProviderTest.java
  src/test/java/com/evenly/took/feature/auth/client/google/GoogleTokenProviderTest.java
  src/test/java/com/evenly/took/feature/auth/client/google/GoogleUserClientTest.java
  src/test/java/com/evenly/took/feature/auth/client/google/GoogleUserInfoProviderTest.java
  src/test/java/com/evenly/took/feature/auth/client/kakao/KakaoTokenProviderTest.java
  src/test/java/com/evenly/took/feature/auth/client/kakao/KakaoUserInfoProviderTest.java
  src/test/java/com/evenly/took/global/aws/s3/S3ServiceTest.java
  src/test/java/com/evenly/took/global/config/testcontainers/S3TestConfig.java
Labels: size/XL

#47 [Feat] 명함에 필요한 Entity 추가
  src/main/java/com/evenly/took/feature/card/domain/Card.java
  src/main/java/com/evenly/took/feature/card/domain/Career.java
  src/main/java/com/evenly/took/feature/card/domain/vo/Content.java
  src/main/java/com/evenly/took/feature/card/domain/vo/Project.java
  src/main/java/com/evenly/took/feature/card/domain/vo/SNS.java
  src/main/java/com/evenly/took/feature/card/dto/response/ContentResponse.java
  src/main/java/com/evenly/took/feature/card/dto/response/ProjectResponse.java
  src/main/java/com/evenly/took/feature/card/dto/response/SNSResponse.java
  src/main/java/com/evenly/took/feature/user/domain/User.java
  src/main/java/com/evenly/took/global/config/swagger/SwaggerConfig.java
Labels: ✨ Feature, size/L

#48 [Deploy] nginx 무중단 배포 작업
  .github/workflows/cd.develop.yml
Labels: size/XS

#51 [Feat] 사용자 정보를 컨트롤러 메서드에 주입하는 LoginUserArgumentResolver 구현
  src/main/java/com/evenly/took/feature/auth/api/AuthController.java
  src/main/java/com/evenly/took/feature/auth/application/TokenProvider.java
  src/main/java/com/evenly/took/global/auth/meta/LoginUser.java
  src/main/java/com/evenly/took/global/auth/resolver/LoginUserArgumentResolver.java
  src/main/java/com/evenly/took/global/config/web/WebConfig.java
Labels: ✨ Feature, size/M

#52 [Feat] 블로그 및 프로젝트 페이지 크롤링
  build.gradle
  src/main/java/com/evenly/took/feature/card/application/LinkExtractor.java
  src/main/java/com/evenly/took/feature/card/client/CrawledType.java
  src/main/java/com/evenly/took/feature/card/client/CrawlerComposite.java
  src/main/java/com/evenly/took/feature/card/client/LinkCrawler.java
  src/main/java/com/evenly/took/feature/card/client/crawler/BasicLinkCrawler.java
  src/main/java/com/evenly/took/feature/card/client/crawler/BrunchLinkCrawler.java
  src/main/java/com/evenly/took/feature/card/client/crawler/VelogLinkCrawler.java
  src/main/java/com/evenly/took/feature/card/client/dto/CrawledDto.java
  src/main/java/com/evenly/took/feature/card/exception/CardErrorCode.java
Labels: ✨ Feature, size/L

#54 [Feat] 명함 커리어 전체 조회 API
  build.gradle
  src/main/java/com/evenly/took/feature/card/api/CardApi.java
  src/main/java/com/evenly/took/feature/card/api/CardController.java
  src/main/java/com/evenly/took/feature/card/application/CardService.java
  src/main/java/com/evenly/took/feature/card/dao/CardRepository.java
  src/main/java/com/evenly/took/feature/card/dao/CareerRepository.java
  src/main/java/com/evenly/took/feature/card/domain/Career.java
  src/main/java/com/evenly/took/feature/card/dto/response/CareerResponse.java
  src/main/java/com/evenly/took/feature/card/dto/response/CareersResponse.java
  src/main/java/com/evenly/took/feature/card/mapper/CareersMapper.java
  src/main/java/com/evenly/took/feature/common/model/BaseTimeEntity.java
  src/main/java/com/evenly/took/global/auth/AuthenticationFilter.java
  src/test/java/com/evenly/took/feature/card/api/CardIntegrationTest.java
  src/test/java/com/evenly/took/feature/card/application/CardServiceTest.java
  src/test/java/com/evenly/took/global/config/testcontainers/MySQLTestConfig.java
  src/test/java/com/evenly/took/global/helper/DatabaseInitializer.java
  src/test/java/com/evenly/took/global/integration/IntegrationTest.java
  src/test/java/com/evenly/took/global/service/ServiceTest.java
  src/test/resources/init.sql
Labels: ✨ Feature, size/XL

#57 [Feat] 특정 명함의 모든 상세 정보를 조회
  build.gradle
  src/main/java/com/evenly/took/feature/card/api/CardApi.java
  src/main/java/com/evenly/took/feature/card/api/CardController.java
  src/main/java/com/evenly/took/feature/card/application/CardService.java
  src/main/java/com/evenly/took/feature/card/dao/CardRepository.java
  src/main/java/com/evenly/took/feature/card/dto/request/CardDetailRequest.java
  src/main/java/com/evenly/took/feature/card/dto/response/CardDetailResponse.java
  src/main/java/com/evenly/took/feature/card/dto/response/ContentResponse.java
  src/main/java/com/evenly/took/feature/card/dto/response/ProjectResponse.java
  src/main/java/com/evenly/took/feature/card/dto/response/SNSResponse.java
  src/main/java/com/evenly/took/feature/card/exception/CardErrorCode.java
  src/main/java/com/evenly/took/feature/card/mapper/CardMapper.java
  src/test/java/com/evenly/took/feature/card/api/CardIntegrationTest.java
  src/test/java/com/evenly/took/feature/card/application/CardServiceTest.java
  src/test/java/com/evenly/took/global/domain/TestUserFactory.java
Labels: ✨ Feature, ✅ Test, size/L

#60 [Feat] Docker 배포 환경 KST 적용
  Dockerfile
Labels: 🚀 Deploy, size/XS

#53 [Feat] 명함 추가 API 구현
  src/main/java/com/evenly/took/feature/auth/api/AuthApi.java
  src/main/java/com/evenly/took/feature/card/api/CardApi.java
  src/main/java/com/evenly/took/feature/card/api/CardController.java
  src/main/java/com/evenly/took/feature/card/application/CardService.java
  src/main/java/com/evenly/took/feature/card/dao/CardRepository.java
  src/main/java/com/evenly/took/feature/card/domain/Card.java
  src/main/java/com/evenly/took/feature/card/domain/Career.java
  src/main/java/com/evenly/took/feature/card/dto/request/CreateCardRequest.java
  src/main/java/com/evenly/took/feature/card/exception/CardErrorCode.java
  src/main/java/com/evenly/took/feature/card/mapper/ContentMapper.java
  src/main/java/com/evenly/took/feature/card/mapper/ProjectMapper.java
  src/main/java/com/evenly/took/feature/card/mapper/SnsMapper.java
  src/main/java/com/evenly/took/feature/common/exception/CommonErrorCode.java
  src/main/java/com/evenly/took/feature/user/domain/User.java
  src/main/java/com/evenly/took/global/exception/GlobalExceptionHandler.java
  src/main/java/com/evenly/took/global/health/HealthApi.java
  src/main/java/com/evenly/took/global/request/StringToListObjectConverter.java
  src/test/java/com/evenly/took/feature/card/api/CardIntegrationTest.java
  src/test/java/com/evenly/took/feature/card/application/CardServiceTest.java
Labels: ✨ Feature, ✅ Test, size/L

#61 [Fix] Docker chrome driver 위치 설정 변경
  src/main/java/com/evenly/took/feature/card/client/crawler/WebDriverManager.java
  src/main/resources/application.yml
Labels: size/XS

#64 [Fix] 동적 크롤링 시 서버 메모리 부족 문제 해결
  .github/workflows/ci.yml
  Dockerfile
  build.gradle
  src/main/java/com/evenly/took/feature/card/client/crawler/BehanceLinkCrawler.java
  src/main/java/com/evenly/took/feature/card/client/crawler/WebDriverHandler.java
  src/main/java/com/evenly/took/feature/card/client/crawler/WebDriverManager.java
  src/main/resources/application-local.yml
  src/main/resources/application.yml
  src/test/resources/application-test.yml
Labels: 🐛 Fix, size/M

#66 [Feat] FCM 푸시알림 초기 설계
  build.gradle
  src/main/java/com/evenly/took/feature/auth/application/AuthService.java
  src/main/java/com/evenly/took/feature/notification/config/FcmConfig.java
  src/main/java/com/evenly/took/feature/notification/domain/DevicePlatform.java
  src/main/java/com/evenly/took/feature/notification/domain/Notification.java
  src/main/java/com/evenly/took/feature/notification/domain/UserDevice.java
  src/main/java/com/evenly/took/feature/notification/exception/NotificationErrorCode.java
  src/main/java/com/evenly/took/feature/user/domain/User.java
  src/main/resources/application.yml
  src/test/java/com/evenly/took/TookApplicationTests.java
  src/test/java/com/evenly/took/feature/card/api/CardIntegrationTest.java
  src/test/java/com/evenly/took/global/aws/s3/S3ServiceTest.java
  src/test/java/com/evenly/took/global/config/FcmTestConfig.java
  src/test/java/com/evenly/took/global/config/TestConfig.java
  src/test/java/com/evenly/took/global/controller/ControllerTest.java
  src/test/java/com/evenly/took/global/helper/DatabaseCleaner.java
  src/test/java/com/evenly/took/global/integration/IntegrationTest.java
  src/test/java/com/evenly/took/global/redis/RedisServiceTest.java
  src/test/java/com/evenly/took/global/service/ServiceTest.java
  src/test/resources/application-test.yml
Labels: ✨ Feature, size/L

#70 [Fix] FCM 키 파일 읽기 방식 변경
  .gitignore
  src/main/java/com/evenly/took/feature/notification/config/FcmConfig.java
  src/main/resources/application.yml
  src/test/resources/application-test.yml
Labels: 🐛 Fix, size/S

#72 [Feat] 폴더 기본 CRUD API 추가
  src/main/java/com/evenly/took/feature/card/api/CardApi.java
  src/main/java/com/evenly/took/feature/card/api/CardController.java
  src/main/java/com/evenly/took/feature/card/application/CardService.java
  src/main/java/com/evenly/took/feature/card/dao/FolderRepository.java
  src/main/java/com/evenly/took/feature/card/domain/Folder.java
  src/main/java/com/evenly/took/feature/card/dto/request/AddCardRequest.java
  src/main/java/com/evenly/took/feature/card/dto/request/AddFolderRequest.java
  src/main/java/com/evenly/took/feature/card/dto/request/FixFolderRequest.java
  src/main/java/com/evenly/took/feature/card/dto/request/RemoveFolderRequest.java
  src/main/java/com/evenly/took/feature/card/dto/response/FolderResponse.java
  src/main/java/com/evenly/took/feature/card/dto/response/FoldersResponse.java
  src/main/java/com/evenly/took/feature/card/exception/FolderErrorCode.java
  src/main/java/com/evenly/took/feature/card/mapper/FolderMapper.java
  src/main/java/com/evenly/took/global/response/SuccessResponse.java
Labels: size/L

#79 [Fix] 애플 인증키 파일 경로 관리되도록 수정
  .gitignore
  src/main/java/com/evenly/took/feature/auth/client/apple/AppleTokenProvider.java
  src/main/java/com/evenly/took/feature/auth/config/properties/AppleProperties.java
  src/main/resources/application.yml
  src/test/java/com/evenly/took/feature/auth/client/apple/AppleTokenProviderTest.java
Labels: size/M

#77 [Feat] 로그아웃 및 회원탈퇴 기능 구현
  src/main/java/com/evenly/took/feature/auth/api/AuthApi.java
  src/main/java/com/evenly/took/feature/auth/api/AuthController.java
  src/main/java/com/evenly/took/feature/auth/application/AuthService.java
  src/main/java/com/evenly/took/feature/auth/application/TokenProvider.java
  src/main/java/com/evenly/took/feature/auth/application/UuidTokenProvider.java
  src/main/java/com/evenly/took/feature/auth/application/WithdrawService.java
  src/main/java/com/evenly/took/feature/auth/exception/AuthErrorCode.java
  src/main/java/com/evenly/took/feature/card/api/CardController.java
  src/main/java/com/evenly/took/feature/card/application/CardService.java
  src/main/java/com/evenly/took/feature/card/dao/CardRepository.java
  src/main/java/com/evenly/took/feature/card/dao/FolderRepository.java
  src/main/java/com/evenly/took/feature/card/dao/ReceivedCardFolderRepository.java
  src/main/java/com/evenly/took/feature/card/dao/ReceivedCardRepository.java
  src/main/java/com/evenly/took/feature/user/application/UserService.java
  src/main/java/com/evenly/took/feature/user/domain/User.java
  src/main/java/com/evenly/took/global/auth/AuthenticationFilter.java
  src/main/java/com/evenly/took/global/auth/meta/PublicApi.java
  src/main/java/com/evenly/took/global/auth/meta/SecuredApi.java
  src/main/java/com/evenly/took/global/health/HealthController.java
  src/test/java/com/evenly/took/feature/auth/api/AuthIntegrationTest.java
  src/test/java/com/evenly/took/feature/auth/application/AuthServiceTest.java
  src/test/java/com/evenly/took/feature/auth/application/WithdrawServiceTest.java
  src/test/java/com/evenly/took/feature/card/api/CardIntegrationTest.java
Labels: ✨ Feature, ✅ Test, size/XL

#82 [Feat] 카카오 로그인 보안 강화 작업
  src/main/java/com/evenly/took/feature/auth/application/WithdrawService.java
  src/main/java/com/evenly/took/feature/auth/client/kakao/dto/request/KakaoTokenRequest.java
  src/main/java/com/evenly/took/feature/auth/config/properties/KakaoProperties.java
  src/main/java/com/evenly/took/feature/auth/domain/OAuthIdentifier.java
  src/main/java/com/evenly/took/feature/user/domain/User.java
  src/main/resources/application.yml
Labels: ✨ Feature

#86 [Test] 공유 받은 명함 및 폴더 관리 테스트
  src/main/java/com/evenly/took/feature/card/api/CardController.java
  src/main/java/com/evenly/took/feature/card/dao/ReceivedCardFolderRepository.java
  src/main/java/com/evenly/took/feature/user/domain/User.java
  src/test/java/com/evenly/took/feature/card/api/CardIntegrationTest.java
  src/test/java/com/evenly/took/feature/card/mapper/CardMapperTest.java
  src/test/java/com/evenly/took/global/domain/CardFixture.java
  src/test/java/com/evenly/took/global/domain/FolderFixture.java
  src/test/java/com/evenly/took/global/domain/ReceivedCardFixture.java
  src/test/java/com/evenly/took/global/domain/ReceivedCardFolderFixture.java
  src/test/java/com/evenly/took/global/domain/UserBase.java
  src/test/java/com/evenly/took/global/domain/UserFactory.java
  src/test/java/com/evenly/took/global/domain/UserFixture.java
  src/test/java/com/evenly/took/global/helper/DatabaseManager.java
  src/test/java/com/evenly/took/global/helper/MysqlCleaner.java
  src/test/java/com/evenly/took/global/integration/JwtMockIntegrationTest.java
Labels: size/XXL
